apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: "Prometheus"
      type: prometheus
      uid: prometheus
      url: http://kube-prometheus-stack-prometheus.observability:9090/
      access: proxy
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s
    - name: "Alertmanager"
      type: alertmanager
      uid: alertmanager
      url: http://kube-prometheus-stack-alertmanager.observability:9093/
      access: proxy
      jsonData:
        handleGrafanaManagedAlerts: false
        implementation: prometheus
    - name: "Loki"
      type: loki
      uid: loki
      url: http://loki-gateway.observability:80
      access: proxy
      jsonData:
        maxLines: 1000
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"datasource.yaml":"apiVersion: 1\ndatasources:\n- name: \"Prometheus\"\n  type: prometheus\n  uid: prometheus\n  url: http://kube-prometheus-stack-prometheus.observability:9090/\n  access: proxy\n  isDefault: true\n  jsonData:\n    httpMethod: POST\n    timeInterval: 30s\n- name: \"Alertmanager\"\n  type: alertmanager\n  uid: alertmanager\n  url: http://kube-prometheus-stack-alertmanager.observability:9093/\n  access: proxy\n  jsonData:\n    handleGrafanaManagedAlerts: false\n    implementation: prometheus\n- name: \"Loki\"\n  type: loki\n  uid: loki\n  url: http://loki-gateway.observability:80\n  access: proxy\n  jsonData:\n    maxLines: 1000"},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"kube-prometheus-stack","meta.helm.sh/release-namespace":"observability"},"creationTimestamp":"2026-06-14T20:51:08Z","labels":{"app":"kube-prometheus-stack-grafana","app.kubernetes.io/instance":"kube-prometheus-stack","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/part-of":"kube-prometheus-stack","app.kubernetes.io/version":"86.2.3","chart":"kube-prometheus-stack-86.2.3","grafana_datasource":"1","heritage":"Helm","release":"kube-prometheus-stack"},"name":"kube-prometheus-stack-grafana-datasource","namespace":"observability","resourceVersion":"34545","uid":"3ffdb366-8bd4-403d-9c7e-391e385f8558"}}
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: observability
  creationTimestamp: "2026-06-14T20:51:08Z"
  labels:
    app: kube-prometheus-stack-grafana
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 86.2.3
    chart: kube-prometheus-stack-86.2.3
    grafana_datasource: "1"
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-stack-grafana-datasource
  namespace: observability
  resourceVersion: "430759"
  uid: 3ffdb366-8bd4-403d-9c7e-391e385f8558
